// Automatically generated by CoffeeConsole 2 of Chrome (Windows) or Chromium(Linux)

var k, key, languages, march_to_may, mon, months, name, nested_hash, simple_hash, v, value, _i, _j, _len, _len1;

languages = ["JavaScript", "Ruby", "Python", "PHP"];

console.log(languages[0]);

for (_i = 0, _len = languages.length; _i < _len; _i++) {
  name = languages[_i];
  console.log(name);
}

months = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];

march_to_may = months.slice(2, 5);

for (_j = 0, _len1 = march_to_may.length; _j < _len1; _j++) {
  mon = march_to_may[_j];
  console.log(mon);
}

simple_hash = {
  one: 1,
  "two": 2,
  three: '3 in string'
};

console.log("one ==> " + simple_hash['one']);

for (key in simple_hash) {
  value = simple_hash[key];
  console.log("" + key + " => " + value);
}

for (k in simple_hash) {
  v = simple_hash[k];
  console.log('%s -> %s', k, v);
}

nested_hash = {
  voice: {
    name: "Josh Timonen",
    age: 30
  },
  tech: {
    name: "Andrew Chalkley",
    age: 28
  }
};

for (k in nested_hash) {
  v = nested_hash[k];
  console.log('%s => %s', k, v);
}

console.log("voice: name => " + nested_hash['voice']['name']);
